apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: ibm-bank
  labels:
    app: customer
    service: customer
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: customer
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
  namespace: ibm-bank
  labels:
    app: customer
    version: v1
spec:
  selector:
    matchLabels:
      app: customer
  replicas: 1
  template:
    metadata:
      labels:
        app: customer
        version: v1
    spec:
      containers:
        - name: customer
          image: docker.io/src32/ibm-bank-customer:v0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: tonyfieit75-pull-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer-ingress
  namespace: ibm-bank
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ibm-bank.detera.local
      http:
        paths:
          - path: /api/v1/customer
            pathType: Prefix
            backend:
              service:
                name: portal
                port:
                  number: 8080
